services:
  # --- THE DATABASE ---
  tools-firefly-db:
    build:
      context: .
      dockerfile_inline: FROM postgres:15-alpine
    image: ${FIN_DB_SERVICE_NAME}
    container_name: ${FIN_DB_SERVICE_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tools-network
    volumes:
      - tools-firefly-db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  # --- FINANCE TRACKER ---
  tools-firefly:
    build:
      context: .
      dockerfile_inline: FROM fireflyiii/core:latest
    container_name: ${FIN_SERVICE_NAME}
    image: ${FIN_SERVICE_NAME}
    ports:
      - "${FIREFLY_PORT}:8080"
    env_file:
      - .env
    networks:
      - tools-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - tools-firefly-data:/var/www/html/storage
      - tools-firefly-data:/var/www/html/export
      - tools-firefly-data:/var/www/html/storage/upload
  
  # --- PDF UTILITY ---
  tools-bentopdf:
    build:
      context: .
      dockerfile_inline: FROM bentopdf/bentopdf:latest
    container_name: tools-bentopdf
    image: tools-bentopdf
    ports:
      - "${BENTOPDF_PORT}:8080"
    networks:
      - tools-network
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped


networks:
  tools-network:
    name: tools-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.5.0.0/24

volumes:
  tools-firefly-db-data:
    name: tools-firefly-db-data
  tools-firefly-data:
    name: tools-firefly-data